name: Build

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: {% raw %}${{ matrix.python_version }}{% endraw %}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --python {% raw %}${{ matrix.python_version }}{% endraw %} --dev
    - name: Test with pytest
      env:
        CODECOV_TOKEN: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
      run: |
        pipenv run pytest --cov={{cookiecutter.package_name}}/
        pipenv run codecov

  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - name: Release on PyPI
      env:
        FLIT_USERNAME: {% raw %}${{ secrets.FLIT_USERNAME }}{% endraw %}
        FLIT_PASSWORD: {% raw %}${{ secrets.FLIT_PASSWORD }}{% endraw %}
      run: |
        pipenv run flit publish
